---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
#      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: mixed-line-ending
      #- id: check-yaml
      - id: pretty-format-json
        args: ["--autofix"]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.1
    hooks:
      - id: check-jsonschema
        name: "Check GitHub Workflows"
        files: ^\.github/workflows/[^/]+$
        types: [yaml]
        args: ["--schemafile", "https://json.schemastore.org/github-workflow"]
      - id: check-jsonschema
        name: "Check Devcontainer"
        files: ^src/.*/\.devcontainer/devcontainer.json
        args: ["--schemafile", "https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.base.schema.json"]
